version: 2.1

jobs:
  code-checks:
    docker:
      - image: cimg/node:18.15.0
    steps:
      - checkout
      - run:
          name: "Install Dependencies"
          command: pnpm i
      - run:
          name: "Run type checks"
          command: pnpm type-check
      - run:
          name: "Run lint checks"
          command: pnpm lint-check

workflows:
  run-code-checks:
    jobs:
      - code-checks